/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThaiTea;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PemesananThaiTea extends javax.swing.JFrame {
    public Connection con;
    public Statement stat;
    private ResultSet res;
    
    int biasa, bubble, harga_jual, jlh_beli, total_harga, uang_bayar, uang_kembali;
    /**
     * Creates new form PemesananThaiTea
     */
public PemesananThaiTea() {
        initComponents();
        koneksi();
        tabel();
        kosongkan();
    }

private void koneksi() {
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/thaiteadb", "root", "");
        stat = con.createStatement();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

private void tabel() {
    DefaultTableModel tb = new DefaultTableModel();
    tb.addColumn("Hari/Tanggal");
    tb.addColumn("Nomor Antrian");
    tb.addColumn("Nama Pembeli");
    tb.addColumn("Jumlah Beli");
    tb.addColumn("Total Bayar");
    tb.addColumn("Uang Bayar");
    tb.addColumn("Uang Kembali");
    tabel.setModel(tb);
    try {
        res = stat.executeQuery("select * from jual_beli");
    while (res.next()) {
        tb.addRow(new Object[]{
            res.getString("Hari_Tanggal"),
            res.getInt("Nomor_Antrian"),
            res.getString("Nama_Pembeli"),
            res.getInt("Jumlah_Beli"),
            res.getDouble("Total_Bayar"),
            res.getDouble("Uang_Bayar"),
            res.getDouble("Uang_Kembali")
            
        });
    }
    } catch (Exception e) {
    }
}

private void kosongkan() {
    nama.setText("");
    antrian.setText("");
    jumlah.setText("");
    total.setText("");
    bayar.setText("");
    harga.setText("");
    kembali.setText("");
    varian.setSelectedItem("Pilih");
    buttonGroup1.clearSelection();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        varian = new javax.swing.JComboBox<>();
        rbBiasa = new javax.swing.JRadioButton();
        rbBubble = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        kembali = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        antrian = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        teks = new javax.swing.JTextArea();
        cetak = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel12.setText("jLabel12");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 24)); // NOI18N
        jLabel1.setText("Penjualan Thai Tea");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Data Thai Tea", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Varian");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tambahan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Harga");

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        varian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        varian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Coklat", "Strawberry", "Red Velvet", "Vanilla" }));
        varian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varianActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBiasa);
        rbBiasa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBiasa.setText("Biasa");
        rbBiasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBiasaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBubble);
        rbBubble.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBubble.setText("Bubble");
        rbBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBubbleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbBubble)
                    .addComponent(varian, 0, 150, Short.MAX_VALUE)
                    .addComponent(rbBiasa)
                    .addComponent(harga))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(varian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbBiasa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbBubble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nomor Antrian");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nama Pembeli");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah beli");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Total Bayar");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Uang Bayar");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Uang Kembali");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        keluar.setBackground(new java.awt.Color(153, 153, 153));
        keluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        keluar.setForeground(new java.awt.Color(0, 0, 102));
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 80, -1));

        simpan.setBackground(new java.awt.Color(153, 153, 153));
        simpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(0, 0, 153));
        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 90, -1));

        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 160, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 160, -1));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 160, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 160, -1));

        antrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antrianActionPerformed(evt);
            }
        });
        jPanel1.add(antrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, -1));

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahKeyReleased(evt);
            }
        });
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 160, -1));

        tabel.setBackground(new java.awt.Color(204, 255, 204));
        tabel.setForeground(new java.awt.Color(102, 102, 255));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabel.setGridColor(new java.awt.Color(51, 51, 255));
        tabel.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 640, 190));

        jLabel11.setText("Hari/Tanggal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, 20));

        tanggal.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 110, 30));

        teks.setColumns(20);
        teks.setRows(5);
        teks.setText("    Struk Belanja Kamu");
        jScrollPane2.setViewportView(teks);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 220, 270));

        cetak.setBackground(new java.awt.Color(153, 153, 153));
        cetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cetak.setForeground(new java.awt.Color(0, 0, 153));
        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel1.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void antrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antrianActionPerformed
        // TODO add your handling code here:
    try {
        res = stat.executeQuery("select * from jual_beli where " + "Nomor_Antrian='" + antrian.getText() + "'");
        while (res.next()) {
            nama.setText(res.getString("Nama_Pembeli"));
            jumlah.setText(res.getString("Jumlah_Beli"));
            total.setText(res.getString("Total_Bayar"));
            bayar.setText(res.getString("Uang_Bayar"));
            kembali.setText(res.getString("Uang_Kembali"));
            tanggal.setText(res.getString("Hari_Tanggal"));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_antrianActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void varianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varianActionPerformed
        // TODO add your handling code here:
        if (varian.getSelectedItem().equals("Pilih Varian")){
            buttonGroup1.clearSelection();
            harga.setText("");
        }
        else if(varian.getSelectedItem().equals("Coklat")) {
            biasa = 8000;
            bubble = 10000;
        }
        else if(varian.getSelectedItem().equals("Strawberry")) {
            biasa = 9000;
            bubble = 12000;
        }
        else if(varian.getSelectedItem().equals("Red Velvet")) {
            biasa = 10000;
            bubble = 15000;
        }
        else if(varian.getSelectedItem().equals("Vanilla")) {
            biasa = 8000;
            bubble = 10000;
        }
        
    }//GEN-LAST:event_varianActionPerformed

    private void rbBiasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBiasaActionPerformed
        // TODO add your handling code here:
        if (rbBiasa.isSelected()){
        harga.setText(String.valueOf(biasa));
        
        
    }
    }//GEN-LAST:event_rbBiasaActionPerformed

    private void rbBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBubbleActionPerformed
        // TODO add your handling code here:
        if (rbBubble.isSelected()){
        harga.setText(String.valueOf(bubble));
        }
    }//GEN-LAST:event_rbBubbleActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        jlh_beli = Integer.parseInt(jumlah.getText());
        harga_jual = Integer.parseInt(harga.getText());
        total_harga = jlh_beli*harga_jual;
        total.setText(String.valueOf(total_harga));
    }//GEN-LAST:event_jumlahActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
        uang_bayar = Integer.parseInt(bayar.getText());
        uang_kembali = Integer.parseInt(total.getText());
        total_harga = uang_bayar - uang_kembali;
        kembali.setText(String.valueOf(total_harga));
    }//GEN-LAST:event_bayarActionPerformed

    private void jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyReleased
        // TODO add your handling code here:
        int x, y, z;
        x =Integer.valueOf(harga.getText());
        y = Integer.valueOf(jumlah.getText());
        z = x * y;
        total.setText("" + z);
        
        
        
    }//GEN-LAST:event_jumlahKeyReleased

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:
        int x, y, z;
        x =Integer.valueOf(bayar.getText());
        y = Integer.valueOf(total.getText());
        z = x - y;
        kembali.setText("" + z);
    }//GEN-LAST:event_bayarKeyReleased

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(null, "Anda yakin keluar?", "keluar", JOptionPane.OK_OPTION);
        if(pilihan == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
    try {
        stat.executeUpdate("insert into jual_beli(Nomor_Antrian, Nama_Pembeli, Jumlah_Beli, Total_Bayar, Uang_Bayar, Uang_Kembali, Hari_Tanggal) values ("
                + "'" + antrian.getText() + "',"
                + "'" + nama.getText() + "',"
                + "'" + jumlah.getText() + "',"
                + "'" + total.getText() + "',"
                + "'" + bayar.getText() + "',"        
                + "'" + kembali.getText() + "',"
                + "'" + tanggal.getText() + "')");
        kosongkan();
        tabel();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan...");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Keterangan Error : " + e);
    }        
        
    
    }//GEN-LAST:event_simpanActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_hargaActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
      try {  
            teks.setText(
            "Struk Belanja Kamu" + "\n" + "\n" +
            "Hari/Tanggal   : " + tanggal.getText() + "\n" +
            "Nomor Antrian  : " + antrian.getText() + "\n" + 
            "Nama Pembeli   :" + nama.getText() + "\n" +
            "Jumlah Beli    :" + jumlah.getText() + "\n " +
            "Total Bayar    :" + total.getText() + "\n" +
            "Uang Bayar     :" + bayar.getText() + "\n" +
            "Uang Kembali   :" + kembali.getText() + "\n" +  
            "-Selamat Menikmati-");
      }catch (Exception e){
          JOptionPane.showMessageDialog(null, "Keterangan Error : " + e);
      }    
    }//GEN-LAST:event_cetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananThaiTea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananThaiTea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananThaiTea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananThaiTea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananThaiTea().setVisible(true);
         }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antrian;
    private javax.swing.JTextField bayar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetak;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rbBiasa;
    private javax.swing.JRadioButton rbBubble;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextArea teks;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<String> varian;
    // End of variables declaration//GEN-END:variables

    
}
